# Generated by Django 3.1.6 on 2021-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_text', models.TextField()),
                ('event_image', models.ImageField(upload_to='post_image/')),
            ],
        ),
    ]
